### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by sarbbottam**
I believe, the [actual branch](https://github.com/sarbbottam/webpack-validator/tree/restructure) might be more helpful in reviewing than the [diff](https://github.com/jonathanewerner/webpack-validator/pull/7/files).

* refactor(scripts): updated npm scripts
* refactor(code): moved properties/*/index.js to properties/*
* refactor(test): moved all test files to /test
* refactor(mocha): moved mocha-setup from src to test
* refactor(mochasetup): moved mocha setup

**What is the motivation behind this restructure?**
Since the code base is increasing, it would be helpful for the new contributors (like me), to get used to the code quickly, less files to consider while scanning the `src/`, a psychological boost up, w.r.t. the **number of files**.

### CODE REVIEW

**Comment by jonathanewerner** [comment]
Hey Sarbbotam, 
thanks for investing your time, but as i explained in the other thread i like it a lot more to have tests next to implementation, just like i put docstrings directly above corresponding functions -- i've just really grown to like colocation. :)
So i'll close this PR.

**Comment by sarbbottam** [comment]
No worries! I would close the issue, not sure if you have noticed the motivation, I have been updating the description after raising the PR.

>>**What is the motivation behind this restructure?**
Since the code base is increasing, it would be helpful for the new contributors (like me), to get used to the code quickly, less files to consider while scanning the `src/`, a psychological boost up, w.r.t. the **number of files**.

**Comment by jonathanewerner** [comment]
Ah, no , hadn't seen that paragraph. Interesting point. On the other hand, when new to a codebase, tests are the primary documentation -- so I'd argue that having tests next to code would be especially helpful in that case. Anyways, feel free to create issues or prs if something in the code is unclear, it was pretty much jotted down in 1-2 days so far. ;)

**Comment by sarbbottam** [comment]
My :dollar: 0.02.

>> when new to a codebase, tests are the primary documentation

I guess it depends, I start with `package.json:main` or `index.js` and then drill down, as and when references to other files are made, similar to an `interpreter`.

*Even though tests are being considered as primary documentation, they are being searched for in `src` directory. I am afraid, but it seems a bit odd to me.*

>> so I'd argue that having tests next to code would be especially helpful in that case

Even in that case, I would have looked for the `tests` in `test/` directory by convention, if existed. 

I see there are many projects are following the convention of co-locating the `test` with `src`, for example, [facebook/react](https://github.com/facebook/react/), they uses `__test__` directory,  along with the source code. However, they do not have any `project root` level directory for `test`.

Having a `test` directory in `project's root` and co-located tests seem to be a bit confusing.
Since `tests` are|will be  co-located the with `src`, it would be better to avoid the `test/` directory in the `project's root` or may be name it to something else. 

Also I would request to move the [mochasetup.js](https://github.com/jonathanewerner/webpack-validator/blob/master/mochasetup.js) from `project's root`, you may refer [the first commit in this PR](https://github.com/jonathanewerner/webpack-validator/pull/7/commits/16017113373e66488d6aaac1eb8fe8fd95afee83).

---
Having said so, I respect your preference and happy to follow the same for this repo. Please excuse me, if I sounded improper.

**Comment by kentcdodds** [comment]
Why don't we put a README in the tests directory explaining how things work in the project?

**Comment by jonathanewerner** [comment]
That sounds reasonable, @kentcdodds.
@sarbbottam, mochasetup.js could arguably be put into test/ , next to mocha.opts. The .test.js extension however is meant for actual test files, not for setup files. It's like a babelrc, hence the placement in the root folder.

**Pull request closed without merging**
