### PR TITLE
feat(lib): Add support for watchOptions

### LINKED ISSUE #60: `watch` options aren't validated
See https://webpack.github.io/docs/cli.html#additional-configuration-options . The validator is missing the `watch` related options.

### PR DESCRIPTION
**Pull request by bebraw**
Implemented as discussed at https://webpack.github.io/docs/cli.html#additional-configuration-options .

Closes #60.

### CODE REVIEW

**Comment by jonathanewerner** [comment]
Cool, LGTM. Could you fix the text for the describe? I'll hit the green button after that. :)

**Comment by bebraw** [comment]
I fixed the text, squashed, and pushed again.

**Comment by bebraw** [comment]
Thanks. If you can do a little version bump in the next day or two, that would be great.

**Comment by jonathanewerner** [comment]
It auto-releases (using `semantic-release` on successful travis master build). https://github.com/jonathanewerner/webpack-validator/releases :)👍🏻

**Pull request merged**
